#!/usr/bin/python


def main():
    from margot.config import MargotConfig
    from margot.database import Base, DatabaseConnection
    config = MargotConfig.from_default_location()
    db_connection = DatabaseConnection.from_config(config)
    db_connection.connect(Base, echo=True)


if __name__ == '__main__':
    main()
